version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pokemon_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: pokemon_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true